name: Deply snowpark apps

#controls when the action will run
on:
  push:
    branches:
      - dev
  #allows manual triggering of the workflow from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: Sugun-ravipalli/snowparkdev
          #path:dev
          ref: dev

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install python packages
        run: pip install -r requrirements.txt

      - name: Deploy Snowpark apps
        working-directory: first_snowpark_project
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT_DEV }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER_DEV }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD_DEV }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE_DEV }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE_DEV }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA_DEV }}
        run: python deploy_snowpark_app.py $GITHUB_WORKSPACE/first_snowpark_project
